blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & discussion
    url: https://github.com/derekturtleroe/Turtle64/discussions
    about: Ask questions or discuss ideas that aren't a specific bug or feature request.
